# Optional, if not provided, the Global LLM will be used
[planning_llm]
model = "claude-sonnet-4-20250514"
api_key = "" # YOUR API KEY

# Optional, if not provided, the Global LLM will be used
[classification_llm]
model = "claude-sonnet-4-20250514"
api_key = "" # YOUR API KEY

# Optional, if not provided, the Global LLM will be used
[execution_llm]
model = "claude-sonnet-4-20250514"
api_key = "" # YOUR API KEY

# Optional, Visual Grounding model, if not provided, the default VG model will be used
[vg_llm]
model_oss = "ByteDance-Seed/UI-TARS-1.5-7B"
# base_url_oss and api_key_oss can be set here or via environment variables
# Uncomment and set these if running vLLM server separately:
# base_url_oss = "http://vllm-server:8005/v1"
# api_key_oss = "infant"

# Optional, File Editing model, if not provided, the default model will be used
[fe_llm]
model = "claude-sonnet-4-20250514"

# Optional, Toolmaker model, if not provided, the default model will be used
[tm_llm]
model = "claude-sonnet-4-20250514"

# Audio parsing model, if not provided, the default model will be used
[ap_llm]
model = "gpt-4o-audio-preview"
api_key = "" # YOUR API KEY