FROM nvidia/cuda:12.2.2-base-ubuntu22.04 

RUN apt-get update && apt-get install -y \
    curl \
    python3 python3-pip \
    && rm -rf /var/lib/apt/lists/*
    
RUN pip3 install vllm


CMD ["vllm", "serve", "ByteDance-Seed/UI-TARS-1.5-7B", "--host", "0.0.0.0", "--port", "8005", "--tensor-parallel-size", "2", "--max-model-len", "8192", "--gpu-memory-utilization", "0.8", "--dtype", "float16", "--api-key", "infant"]